Description of dispMCURV
dispMCURV
PURPOSE
dispMCURV: Normaliza la salida estandar disp en consola de los
SYNOPSIS
function dispMCURV()
DESCRIPTION
 dispMCURV: Normaliza la salida estandar disp en consola de los
 metodos usados por las clases de MCURV
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
HognestadConcrete ______________________________________________________________________
HognestadModifiedConcrete ______________________________________________________________________
ElastoplasticSteel ______________________________________________________________________
ManderSteel ______________________________________________________________________
SectionDesigner ______________________________________________________________________
SOURCE CODE
function dispMCURV()
% dispMCURV: Normaliza la salida estandar disp en consola de los
% metodos usados por las clases de MCURV
fprintf('---------------------------------------------------------------------------\n');
fprintf('\n');
end